### ISSUE TITLE
Pom structure of hudson-plugin-parent:3.0.0 causes issues if the pom is not the direct parent of the plugin pom

### ISSUE THREAD

**Issue by rduncan** [hudson/hudson-2.x#356]
We found a problem in upgrading  a plugin from version 2.1.2 to version 3.0.0.  The 3.0.0 version of hudson-plugin-parent uses the property reference ${project.parent.version} to add dependencies with same version (3.0.0).

This works if the plugin being built uses the hudson-plugin-parent as its direct parent.  In our case, however, we have another parent xxx-hudson-plugin-parent  that parents plugin projects to add company specific settings. It in turn specifies hudson-plugin-parent as its parent.  In this configuration ${project.parent.version} refers to xxx-hudson-plugin-parent's version not hudson-plugin-parent's version and the build fails.

**Comment by bobfoster** [comment]
This is bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=399342

The only workaround is to make your intermediate plugin parent the same version as Hudson, e.g., 3.0.0.

Needs to be escalated for Hudson 3.0.1.

**Comment by wjprakash** [comment]
Bob already fixed this in Hudson 3.0.1

http://git.eclipse.org/c/hudson/org.eclipse.hudson.core.git/commit/?id=3e15ce9499e17d43c207bf7a0070aed14561b1fa
